<?php

namespace Database\Seeders;

use App\Models\SystemSetting;
use App\Models\User;
use Illuminate\Database\Seeder;

class SystemSettingSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $adminId = User::query()->where('role', 'super_admin')->value('id');

        SystemSetting::query()->updateOrCreate(
            ['id' => 1],
            [
                'barangay_name' => 'Barangay San Isidro',
                'barangay_city' => 'Quezon City',
                'barangay_province' => 'Metro Manila',
                'contact_number' => '0917-555-0100',
                'contact_email' => 'barangay.sanisidro@example.com',
                'receipt_prefix' => 'OR-SI',
                'timezone' => 'Asia/Manila',
                'maintenance_mode' => false,
                'footer_note' => 'Generated by Barangay Management System',
                'updated_by' => $adminId,
            ]
        );
    }
}
